name: influxdb
base: core18
# Get version info from the influxdb part's override-build script
adopt-info: influxdb
summary: InfluxDB
description: |
  Scalable datastore for metrics, events, and real-time analytics.

grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  influxdb:
    plugin: dump
    source:
      - on arm64: https://dl.influxdata.com/platform/nightlies/influx_nightly_linux_arm64.tar.gz
      - else: https://dl.influxdata.com/platform/nightlies/influx_nightly_linux_amd64.tar.gz
    override-build: |
      snapcraftctl build
      VERSION=$($SNAPCRAFT_PART_BUILD/influxd version | cut -d' ' -f2)
      snapcraftctl set-version $VERSION
    stage:
      - influxd
  staged:
    plugin: nil
    stage-packages:
      - setpriv
    stage:
      - -lib        # libcap-ng.so.0.0.0 is in base
      - -usr/lib    # don't ship empty dir
      - -usr/share

system-usernames:
  snap_daemon: shared

apps:
  influxd:
    command: usr/bin/setpriv --clear-groups --reuid snap_daemon --regid snap_daemon -- $SNAP/influxd
    environment:
      INFLUXD_CONFIG_PATH: $SNAP_COMMON/conf
    daemon: simple
    plugs:
      - network
      - network-bind

hooks:
  install:
    plugs: []
  post-refresh:
    plugs: []
